"use strict";
exports.__esModule = true;
var person_1 = require("./person");
var person = new person_1.Person();
person.chat();
person.login();
person.chat();
person.login();
person.logout();
person.getState();
